# https://docs.travis-ci.com/user/languages/c/

language: c

os:
  - linux
  - osx

sudo: required

addons:
  apt:
    sources:
    - sourceline: 'ppa:fish-shell/release-2'
    packages:
    - fish

before_install:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install fish

install:
  - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
  - fish -c "fisher fishtape"

script:
  - fish -n **/*.fish # check for syntax issues
  - fish -c "fishtape test/*.test.fish"
